apiVersion: v2
name: monitoring
description: Prometheus + Grafana (no Alertmanager, no TLS)
type: application
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: 62.7.0
    repository: https://prometheus-community.github.io/helm-charts