kube-prometheus-stack:
  namespaceOverride: "monitoring"

  # No Alertmanager
  alertmanager:
    enabled: false

  # Disable control-plane collectors that try to create Services in kube-system
  defaultRules:
    create: true
    rules:
      etcd: false
      kubeScheduler: false
      kubeControllerManager: false
      kubeProxy: false
  kubeEtcd:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeProxy:
    enabled: false
  kubelet:
    enabled: false

  # Prometheus + Grafana minimal
  prometheus:
    enabled: true
    service:
      type: ClusterIP
    prometheusSpec:
      retention: 7d
      scrapeInterval: 15s
      serviceMonitorSelector:
        matchLabels:
          thmanyah.com/monitor: "true"
      podMonitorSelector:
        matchLabels:
          thmanyah.com/monitor: "true"

  grafana:
    enabled: true
    adminPassword: "admin"
    service:
      type: ClusterIP
    ingress:
      enabled: false

  kube-state-metrics:
    enabled: true

  nodeExporter:
    enabled: true
