kube-prometheus-stack:
  alertmanager:
    enabled: false

  prometheus:
    enabled: true
    service:
      type: ClusterIP
    prometheusSpec:
      retention: 7d
      scrapeInterval: 15s
      evaluationInterval: 15s

  grafana:
    enabled: true
    adminPassword: "admin"
    service:
      type: ClusterIP
    ingress:
      enabled: false

  # Scrape kubelet (includes cAdvisor metrics for pod/container CPU/memory)
  kubelet:
    serviceMonitor:
      enabled: true
      https: true
      cAdvisor: true

  # Kubernetes object metrics (pods, deployments, etc.)
  kube-state-metrics:
    enabled: true

  # Node-level metrics (CPU/mem/disk at node level)
  prometheus-node-exporter:
    enabled: true
