apiVersion: v1
kind: Secret
metadata:
  name: auth-db
type: Opaque
stringData:
  DB_HOST: pg-main-primary.thmanyah-auth.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: app
  DB_USER: postgres
  DB_PASSWORD: {{ default "password" ((default dict .Values.db).password) | quote }}
